[window]
opacity = 0.93

[colors.primary]
background = '#000000'
foreground = '#D4D4D4'

[colors.cursor]
text = "#1E1E1E"
cursor = "#D4D4D4"

[colors.normal]
red = "#F44747"
green = "#6A9955"
yellow = "#795E26"
blue = "#007ACC"
magenta = "#C586C0"
cyan = "#4FC1FF"
white = "#D4D4D4"

[font]
size = 18.0

[font.bold]
family = "DejaVu Sans Mono"
style = "Medium Bold,Bold"

[font.bold_italic]
family = "DejaVu Sans Mono"
style = "Medium Bold Italic,Bold Italic"

[font.italic]
family = "DejaVu Sans Mono"
style = "Medium Italic,Italic"

[font.normal]
family = "DejaVu Sans Mono"
style = "Medium Light,Regular"
